/********************************************************************************
     nbtcp_smipp.h - This file contains the structure and function declarations 
                     that need the byte swapping code generated by the SMI 
                     Pre-processor. File nbtcp_smipp.c is generated when the SMI
                     Pre-processor is executed on this file.
 ********************************************************************************/

/*
 * RCS info
 * $Author: steves $
 * $Locker:  $
 * $Date: 2016/03/03 18:53:03 $
 * $Id: nbtcp_smipp.h,v 1.3 2016/03/03 18:53:03 steves Exp $
 * $Revision: 1.3 $
 * $State: Exp $
 */

#ifndef NBTCP_SMI_H
#define NBTCP_SMI_H


#include <prod_user_msg.h>
#include <legacy_prod.h>
#include <nbtcp.h>



/****** SMI Structure Definitions ******/

/*     Product Request Message */

/* SMI_struct Pd_request_products; */  /* refer prod_user_msg.h */
/* SMI_struct msg_header; */
/* SMI_struct RPS_block; */

/*     Bias Table Msg */

/* SMI_struct bias_table_msg_base_t; */
/* SMI_struct Block_id_t; */      /* refer prod_user_msg.h */
/* SMI_struct Memory_span_t; */   /* refer prod_user_msg.h */



/****** SMI Function Definitions ******/


/* SMI_function SWAp_bytes; */

#endif
